version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: scouting-docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/
    links:
      - scouting-db
  scouting-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: timesheet
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql/timesheet.sql:/docker-entrypoint-initdb.d/1timesheet.sql
      - ./sql/test-data.sql:/docker-entrypoint-initdb.d/2test-data.sql
#phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    ports:
#      - "8090:80"
#    environment:
#      PMA_HOST: scouting-db
#      PMA_USER: root
#      PMA_PASSWORD: password
#    depends_on:
#      - scouting-db
